### PR TITLE
Documentation redirects added

### PR DESCRIPTION
**Pull request by rahul799**
Part of #58

### CODE REVIEW

**Comment by jpfeuffer** [comment]
This is not the old behavior.

**Comment by rahul799** [comment]
It seems like the redirects are not working.

**Comment by jpfeuffer** [comment]
Because they are wrong.

**Comment by rahul799** [comment]
@jpfeuffer I think [this](https://github.com/OpenMS/openms.de/pull/69/files#diff-16b6401519950c5f36e2548e217df9174771c97bbfb0c8ead59906fe108d28feR2) entry is correct? So logically https://openms.netlify.app/documentation/wxwxwq must redirect to https://openms.readthedocs.io/en/latest/wxwxwq ?

**Comment by jpfeuffer** [comment]
No, the documentation that we need to link is the API documentation.
https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/

**Pull request merged**
